### ISSUE TITLE
App Library folders don’t appear and there is only blank space below the search bar

### ISSUE THREAD

**Issue by jarboer** [PoomSmart/App-Library-for-iPad#3]
The tweak doesn't seem to fully work for me, the search bar will bring up the app list but no folders are shown on the initial view that is shown which should have folders. Here is a screenshot of what's happening for me:

![image](https://user-images.githubusercontent.com/16063018/120124725-b1a21c80-c183-11eb-8dc9-92e253cd51ba.png)

I'm using an iPad Air 2 on iOS 14.3 using checkra1n.

**Comment by PoomSmart** [comment]
This tweak will be discontinued and the further development would go through https://github.com/tomaszpoliszuk/AppLibraryEnabler
